### ISSUE TITLE
openapi 运行报错了

### ISSUE THREAD

**Issue by alexcjluo** [ShekiLyu/lixinger-openapi#13]
error msg:  api was not found.
可能是理杏仁更改了api。 我试着自己修改了下没成功。烦请作者看看问题出在哪里。谢谢啦。

**Comment by alexcjluo** [comment]
已经解决了。

api 要加上后缀 /non_financial 或者/bank 或者/security 或者/insurance. 但实验表明只要加了其中任何一个，所有数据都可以下载。
metrics 要改成 metricsList。
FYR

**Comment by ShekiLyu** [comment]
很久没有用这个了，也没有登录github，今天才看到你的消息，我会尽快修复问题。多谢~！

**Comment by ShekiLyu** [comment]
我看了一下，我这边代码没有要修改的，因为我这提供的是很底层的api，需要修改的是更上层的代码，也就是传给我这边的参数。
不过我要把使用指南里的示例修改一下。

**Comment by alexcjluo** [comment]
Cool!

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: ShekiLyu <notifications@github.com>
发送时间: Friday, May 15, 2020 11:29:13 AM
收件人: ShekiLyu/lixinger-openapi <lixinger-openapi@noreply.github.com>
抄送: alexcjluo <alexcjluo@hotmail.com>; State change <state_change@noreply.github.com>
主题: Re: [ShekiLyu/lixinger-openapi] openapi 运行报错了 (#13)


我看了一下，我这边代码没有要修改的，因为我这提供的是很底层的api，需要修改的是更上层的代码，也就是传给我这边的参数。
不过我要把使用指南里的示例修改一下。

―
