### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by HGYD** [ShekiLyu/lixinger-openapi#6]
SyntaxError: Non-ASCII character '\xe5' in file lixinger_openapi\json.py on line 3, but no encoding declared... 编码问题？

**Comment by ShekiLyu** [comment]
请问一下你的安装环境和安装方式，我这边在mac和linux安装是没问题的

**Comment by ShekiLyu** [comment]
时间太久了，已经改版了好几回，不跟踪这个问题了。
真实原因是我有强迫症，看着close不了的issue就头疼。
